"""Added BlockListedToken model

Revision ID: 5bd7a20d441c
Revises: c7d05bdd6465
Create Date: 2024-12-13 13:56:20.205949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd7a20d441c'
down_revision = 'c7d05bdd6465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_listed_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_listed_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_listed_tokens_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_listed_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_listed_tokens_jti'))

    op.drop_table('block_listed_tokens')
    # ### end Alembic commands ###
