"""Reinitializing migrations

Revision ID: 7123743a8b77
Revises: 
Create Date: 2025-02-22 15:25:55.730261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7123743a8b77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_listed_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_block_listed_tokens_jti')

    op.drop_table('block_listed_tokens')
    op.drop_table('student')
    op.drop_table('daur')
    with op.batch_alter_table('moallim', schema=None) as batch_op:
        batch_op.drop_index('ix_moallim_email')

    op.drop_table('moallim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moallim',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('its', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('its')
    )
    with op.batch_alter_table('moallim', schema=None) as batch_op:
        batch_op.create_index('ix_moallim_email', ['email'], unique=1)

    op.create_table('daur',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('moallim_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['moallim_id'], ['moallim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('its', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=1), nullable=False),
    sa.Column('daur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['daur_id'], ['daur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('its', 'daur_id', name='uix_its_daur')
    )
    op.create_table('block_listed_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block_listed_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_block_listed_tokens_jti', ['jti'], unique=False)

    # ### end Alembic commands ###
