"""added composite unique constraint

Revision ID: 9937577348be
Revises: 
Create Date: 2024-11-19 22:43:03.342216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9937577348be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_its_daur', ['its', 'daur_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('uix_its_daur', type_='unique')

    # ### end Alembic commands ###
