"""newdb

Revision ID: c7d05bdd6465
Revises: 
Create Date: 2024-11-21 00:09:55.069619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d05bdd6465'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moallim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('its', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('its')
    )
    op.create_table('daur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('moallim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['moallim_id'], ['moallim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('its', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('daur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daur_id'], ['daur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('its', 'daur_id', name='uix_its_daur')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('daur')
    op.drop_table('moallim')
    # ### end Alembic commands ###
